import faiss
from sentence_transformers import SentenceTransformer

qa_data = {
    "What is oseltamivir used to treat?": """Oseltamivir is an antiviral medication, mainly used for the treatment of influenza A and influenza B, and it can also be used for influenza prevention in specific scenarios. It belongs to neuraminidase inhibitors. Its target is neuraminidase on the surface of influenza viruses, which can reduce the release of newly generated viral particles from host cells, thereby reducing the ability of the virus to continue spreading in the respiratory tract.""",
    "What is a neuraminidase inhibitor?": """Neuraminidase inhibitors are a common class of antiviral drugs for influenza, mainly working by inhibiting neuraminidase on the surface of influenza viruses. After influenza viruses replicate, they need neuraminidase to be released from the surface of infected cells and continue infecting other cells; this class of drugs blocks that process. Common examples include oseltamivir, zanamivir, and peramivir.""",
    "What is the difference between baloxavir and oseltamivir?": """Baloxavir and oseltamivir can both be used for antiviral treatment of influenza, but their mechanisms of action are different. Oseltamivir is a neuraminidase inhibitor and mainly affects the process by which viruses are released from host cells; baloxavir acts on the cap-dependent endonuclease in the early stage of influenza virus replication and mainly interferes with viral RNA transcription. Both target influenza viruses, but their pharmacological targets are not the same.""",
    "What is the difference between a cold and the flu?": """The common cold and influenza can both cause respiratory symptoms such as cough, runny nose, nasal congestion, and sore throat, but influenza usually has a more sudden onset and more obvious systemic symptoms. The common cold is mostly caused by rhinoviruses and other viruses, and the symptoms are generally milder; influenza is caused by influenza viruses, with common manifestations including high fever, chills, headache, muscle aches, and marked fatigue. Its transmissibility, seasonality, and risk of complications are usually more prominent.""",
    "Can antibiotics treat the flu?": """Antibiotics are mainly used to treat bacterial infections and cannot directly treat influenza virus infection. The targets of antibiotics are usually structures or processes such as bacterial cell walls, protein synthesis, and nucleic acid metabolism, while influenza viruses do not have these typical bacterial structures. Influenza is a viral infection, and targeting the virus itself usually relies on antiviral drugs or clearance by the immune system, rather than antibiotics.""",
    "Why can vaccines prevent diseases?": """Vaccines allow the immune system to come into contact with key features of pathogens in advance to establish protection, such as viral proteins, bacterial antigens, or information encoding antigens. After vaccination, the human body can produce specific antibodies, T-cell responses, and immune memory. When encountering the same or similar pathogen in the future, the immune system can recognize it more quickly and initiate a response, thereby reducing the risk of infection, severe disease, or transmission.""",
    "What is PCR testing?": """PCR is polymerase chain reaction, a molecular biology technique that amplifies specific nucleic acid fragments. By repeatedly carrying out denaturation, annealing, and extension, it copies very small amounts of DNA or RNA-related sequences in a sample into a large number of copies, making it easier for detection equipment to identify the target fragment. PCR is commonly used in pathogen detection, genetic analysis, tumor-related testing, forensic identification, and basic research.""",
    "What is the difference between DNA and RNA?": """DNA and RNA are both nucleic acids, but their structures, components, and functions are different. DNA is usually a double-stranded structure and is mainly responsible for long-term storage of genetic information; RNA is usually a single-stranded structure and is more involved in genetic information transmission, gene expression regulation, and protein synthesis. In terms of composition, DNA uses deoxyribose and the base T, while RNA uses ribose and the base U.""",
    "Why do people get a fever?": """Fever is a temperature regulation response produced by the human body in response to infection, inflammation, or other stimuli. After immune cells recognize pathogens or tissue damage signals, they release inflammatory mediators such as cytokines. These signals affect the temperature set point in the hypothalamus, causing the body to raise its temperature through chills, vasoconstriction, and metabolic changes. Fever is essentially the result of the combined effects of immune responses and temperature regulation.""",
    "What is the difference between viruses and bacteria?": """Viruses and bacteria are both common pathogens, but their biological characteristics differ greatly. Bacteria are single-celled organisms with cellular structures and can usually metabolize and reproduce independently; viruses do not have complete cellular structures and must enter host cells to use the host cell's materials and systems to replicate themselves. Antibiotics mainly target bacteria, while antiviral drugs usually target steps such as viral entry, replication, and release.""",
    "How does the immune system work?": """The immune system is composed of immune organs, immune cells, and various signaling molecules. It is mainly responsible for recognizing and clearing pathogens, abnormal cells, and foreign substances. Innate immune responses are fast and provide the first line of defense; adaptive immune responses are more specific and can produce antibodies, T-cell responses, and immune memory. The two work together, enabling the human body to respond to infection, injury, and abnormal cellular changes.""",
    "What is an allergic reaction?": """An allergic reaction is a phenomenon in which the immune system overreacts to substances that are usually harmless. These substances are called allergens, such as pollen, dust mites, animal dander, food components, or drug molecules. During an allergy, immune cells release inflammatory mediators such as histamine, causing symptoms such as sneezing, runny nose, rash, itching, cough, airway constriction, or gastrointestinal discomfort.""",
    "What is inflammation?": """Inflammation is a defensive response produced by the body when facing infection, injury, or irritation. Typical processes include local vasodilation, increased blood flow, increased vascular permeability, immune cell accumulation, and release of inflammatory mediators. Inflammation can help clear pathogens, remove damaged cells, and initiate tissue repair. Common manifestations include redness, swelling, heat, pain, and loss of function.""",
    "What does high blood sugar mean?": """High blood sugar means that the concentration of glucose in the blood exceeds the normal range. Glucose is an important source of energy for the human body, mainly derived from carbohydrates in food, and regulated by factors such as insulin, glucagon, liver glycogen breakdown, and tissue glucose uptake capacity. Elevated blood sugar may be related to eating, stress, lack of exercise, insufficient insulin secretion, or insulin resistance.""",
    "What does high blood pressure mean?": """High blood pressure means that the pressure inside the arteries remains at a relatively high level for a long time. Blood pressure is jointly determined by the heart's pumping capacity, vascular elasticity, blood volume, and peripheral vascular resistance. Long-term elevated blood pressure increases the burden on the heart, brain, kidneys, retina, and vascular system, and is often related to genetics, age, diet, body weight, exercise, mental stress, and metabolic status.""",
    "What role does protein play in the human body?": """Protein is an important biological macromolecule in the human body. It is composed of amino acids and has many functions, including structural support, enzyme catalysis, substance transport, immune defense, signal transmission, and muscle contraction. Many enzymes, antibodies, receptors, transport proteins, cytoskeletal components, and some hormones are proteins. The function of a protein depends on its amino acid sequence, spatial structure, and cellular environment.""",
    "What is photosynthesis?": """Photosynthesis is the process by which plants, algae, and some bacteria use light energy to synthesize organic matter. Chlorophyll in plant chloroplasts absorbs sunlight and converts carbon dioxide and water into organic compounds such as glucose, while releasing oxygen. Photosynthesis provides plants themselves with a material and energy foundation, also provides an organic carbon source for ecosystems, and maintains an important source of atmospheric oxygen.""",
    "Why is the sky blue?": """The sky appears blue mainly because of Rayleigh scattering. Sunlight looks close to white, but actually contains visible light of many wavelengths. After sunlight enters Earth's atmosphere, short-wavelength blue light is more easily scattered in all directions by air molecules than long-wavelength red light. When people look at the sky from the ground, what they see is blue scattered light from all directions.""",
    "What is the greenhouse effect?": """The greenhouse effect refers to the phenomenon in which certain gases in the atmosphere absorb infrared radiation released by Earth's surface and re-radiate part of the heat back to the surface and lower atmosphere. Water vapor, carbon dioxide, methane, and nitrous oxide are all important greenhouse gases. A moderate greenhouse effect keeps Earth at a suitable temperature, while an increase in greenhouse gas concentrations changes Earth's energy balance.""",
    "How do earthquakes occur?": """Earthquakes are usually related to the accumulation and sudden release of stress in rocks in Earth's crust. Earth's lithosphere is composed of multiple plates, and plates can collide, stretch apart, or slide past each other. When the stress borne by rocks near a fault exceeds their strength limit, the rock layers suddenly fracture or slip, and the released energy propagates outward in the form of seismic waves, causing the ground to shake.""",
    "Why do volcanoes erupt?": """Volcanic eruptions are usually caused jointly by underground magma activity, gas accumulation, and pressure changes. Partial melting of rocks deep in the mantle or crust forms magma, and magma contains volatile gases such as water vapor, carbon dioxide, and sulfur dioxide. When magma rises and pressure continues to increase, magma and gases erupt onto the surface through fractures or volcanic conduits.""",
    "Why are there four seasons?": """The change of the four seasons is mainly caused by the tilt of Earth's rotation axis and Earth's revolution around the Sun. Earth's rotation axis has a certain tilt relative to the plane of its orbit, so at different times of the year, the point of direct sunlight moves between the Tropic of Cancer and the Tropic of Capricorn. When one hemisphere is tilted toward the Sun, the Sun's altitude angle is higher, the day is longer, and more energy is received, forming summer; when it is tilted away from the Sun, winter forms.""",
    "Why does the Moon have phases?": """The waxing and waning of the Moon is called lunar phase change. The reason is that as the Moon orbits Earth, the Sun always illuminates half of the Moon, while observers on Earth see different proportions of the illuminated part from different positions. During a new moon, most of the illuminated side of the Moon faces away from Earth; during a full moon, most of the illuminated side faces Earth. As the Moon's position changes, lunar phases such as first quarter, full moon, and last quarter appear.""",
    "How does sound propagate?": """Sound is a mechanical wave produced by the vibration of objects and requires a medium to propagate. The vibration of an object drives particles in the surrounding air, water, or solid to undergo periodic compression and rarefaction, and this disturbance propagates outward to form sound waves. The propagation speed of sound differs in different media. It is usually faster in solids, next in liquids, and slower in gases, and it cannot propagate in a vacuum.""",
    "What is electric current?": """Electric current is the directional movement of electric charge. Electric current in metal conductors mainly comes from the directional movement of free electrons under the action of an electric field, while electric current in electrolyte solutions can be formed by the movement of positive and negative ions. The magnitude of current represents the amount of electric charge passing through the cross-section of a conductor per unit time, and its unit is the ampere. The relationship between current, voltage, and resistance is commonly described by Ohm's law.""",
    "What does entropy mean?": """Entropy is a physical quantity in thermodynamics that describes the number of microscopic states, the degree of disorder, or the degree of energy dispersal in a system. The more microscopic arrangements a system can realize, the greater the entropy usually is. The second law of thermodynamics states that in an isolated system, spontaneous processes usually proceed in the direction of increasing total entropy. Entropy is also often used to explain heat conduction, gas diffusion, and energy conversion efficiency.""",
    "What is a black hole?": """A black hole is a celestial region with extremely strong gravity. Within its event horizon, the escape velocity exceeds the speed of light, so even light cannot escape. Black holes can usually form from the collapse of massive stars at the end of their evolution, and they may also exist in supermassive form at the centers of galaxies. A black hole itself does not emit light, but matter around it forms an accretion disk before falling into the black hole and releases intense radiation, allowing it to be observed indirectly.""",
    "What is an atom?": """An atom is one of the basic units that make up ordinary matter. It consists of an atomic nucleus and extranuclear electrons. The atomic nucleus contains protons and neutrons. Protons carry positive charge, neutrons carry no charge, and electrons carry negative charge and are distributed outside the nucleus. Different elements are determined by the number of protons. For example, a hydrogen atom has one proton, and a carbon atom has six protons. Atoms can form molecules, crystals, and various materials through chemical bonds."""
}

qa_data.update({
    "What is Bitcoin?": """Bitcoin is a digital currency system based on a peer-to-peer network, cryptography, and proof of work. It has no central bank, single clearing institution, or unified server, but instead relies on global nodes to jointly maintain a public ledger. The core components of the Bitcoin system include the blockchain, UTXO transaction model, digital signatures, hash functions, proof of work, and economic incentives. Users control funds through private keys. Transactions are signed and then broadcast to the network, verified by nodes, packaged into blocks by miners, and finally become on-chain records.""",
    "Why is Bitcoin decentralized?": """Bitcoin is called decentralized because its ledger maintenance, transaction verification, and block propagation do not depend on a single institution. Anyone can run a full node, independently store blockchain data, and verify transactions and blocks according to public consensus rules. Miners compete to produce blocks, but they cannot arbitrarily create bitcoins that violate the rules or force nodes to accept invalid blocks. Full nodes, miners, users, and developers form checks and balances, so the system's trustworthiness mainly comes from public rules, cryptographic verification, and distributed consensus.""",
    "What is a blockchain?": """A blockchain is a ledger structure that organizes data into blocks in chronological order and connects them with hash pointers. Each block usually contains a block header, the previous block hash, a Merkle root, a timestamp, difficulty-related fields, a nonce, and a batch of transactions. Because a new block references the hash value of the previous block, modifying a historical block would break the hash relationship of subsequent blocks and require redoing a large amount of proof of work. The value of a blockchain lies in making historical records verifiable, tamper-resistant, replicable, and auditable.""",
    "How is a Bitcoin transaction completed?": """A Bitcoin transaction uses existing unspent transaction outputs as inputs and then creates new transaction outputs for the recipient or a change address. The user's wallet selects suitable UTXOs, constructs transaction data, and uses the corresponding private keys to generate digital signatures, proving that the user has the right to spend these inputs. After the transaction is broadcast, full nodes check its format, signatures, script conditions, whether the inputs are unspent, whether the amounts are conserved, and whether the fee is reasonable. Valid transactions enter the node mempool, miners select transactions to package into blocks, and after a block is accepted by the network, the transaction receives confirmations.""",
    "What is a Bitcoin wallet?": """A Bitcoin wallet is not a container that directly stores bitcoins, but a tool that manages private keys, public keys, addresses, and transaction signatures. What is recorded on the blockchain is UTXOs. A wallet scans on-chain data to find spendable outputs belonging to itself and uses private keys to sign transactions. Wallets can be software wallets, hardware wallets, cold wallets, or multisig wallets. Their core functions include generating keys, backing up seeds, deriving addresses, querying balances, constructing transactions, signing transactions, and broadcasting transactions.""",
    "What is the difference between a private key and a public key?": """A private key is the core secret data through which a user controls assets or identity and must be kept confidential; a public key is public data derived from the private key through elliptic curve scalar multiplication and can be given to others for signature verification. A private key can generate a digital signature to prove that a transaction or message is authorized by the private key holder; a public key can verify whether the signature matches the message and the private key. A secure asymmetric cryptographic system requires that deriving the private key from the public key be computationally infeasible, so the private key is responsible for control, and the public key is responsible for verification.""",
    "What is a Bitcoin address?": """A Bitcoin address is a string representation commonly used when receiving bitcoins. It is usually obtained by encoding a public key, public key hash, or script. The address itself is not a private key, nor is it an account balance, but a readable form of an on-chain output locking condition. Sending bitcoins to an address is essentially creating a UTXO on the blockchain that can only be spent by satisfying specific script conditions. Different address formats correspond to different script types, such as legacy addresses, SegWit addresses, and Taproot addresses. They differ in encoding method, transaction structure, and fee efficiency.""",
    "What is a digital signature?": """A digital signature is a cryptographic mechanism generated with a private key and verified with a public key, used to prove message origin, authorization relationship, and data integrity. In Bitcoin, when a user spends a UTXO, they need to generate a signature for a specific digest of the transaction, and nodes then use the corresponding public key to verify whether the signature is valid. A valid signature indicates that the transaction was indeed authorized by the person who controls the private key and that the transaction content covered by the signature has not been tampered with. Early Bitcoin mainly used ECDSA, while Taproot introduced a mechanism based on Schnorr signatures.""",
    "What is the difference between digital signatures and encryption?": """Digital signatures and encryption are both cryptographic technologies, but their goals are different. The main goal of encryption is confidentiality, turning plaintext into ciphertext so that people without the decryption key cannot read the content; the main goal of digital signatures is authentication, authorization, and integrity, proving that a message comes from the private key holder and has not been tampered with. A signature is not simply encrypting a message with a private key, but generating a signature value through mathematical operations on the message digest and the private key, and then verifying it with the public key. Bitcoin transactions use signatures to prove spending authority, not to hide transaction content.""",
    "What is a hash function?": """A hash function is an algorithm that converts input of arbitrary length into output of fixed length. The output is called a hash value or digest. A cryptographic hash function should have preimage resistance, collision resistance, and the avalanche effect, meaning that it is difficult to infer the original text from the hash value, difficult to find two different inputs that produce the same hash value, and a tiny change in the input causes a significant change in the output. Bitcoin uses hash functions to generate transaction identifiers, block identifiers, Merkle tree nodes, and proof-of-work targets. Hash functions are an important foundation for blockchain tamper resistance and efficient verification.""",
    "What is proof of work?": """Proof of work is a mechanism for participating in consensus through computational cost. After constructing a candidate block, Bitcoin miners need to continuously change variable data such as the nonce, timestamp, or transaction combination so that the hash value of the block header is lower than the current difficulty target. Finding a valid hash requires a large amount of repeated computation, but other nodes can verify the result very quickly. Proof of work means that rewriting historical blocks requires paying the corresponding computational cost again and catching up with or exceeding the accumulated work of the honest network, thereby increasing the difficulty of tampering with the ledger and double-spending attacks.""",
    "What is Bitcoin mining?": """Bitcoin mining is the process in which miners collect transactions, construct candidate blocks, perform proof of work, and compete to obtain block rewards. Miners place ordinary transactions and a coinbase transaction into a block. The coinbase transaction is used to claim the block subsidy and transaction fees. Miners continuously try different block header data so that the hash satisfies the difficulty target. After successfully finding a valid block, the miner broadcasts the block to the network, and other nodes accept the block after verifying that it is valid. Mining also plays roles in new block creation, transaction ordering, ledger security, and control of the issuance schedule.""",
    "Why does Bitcoin need confirmations?": """The number of confirmations indicates how many new blocks have been added after the block containing a transaction. When a transaction has just been packaged into a block, it is usually counted as one confirmation. Each subsequent valid block usually increases the difficulty of removing the transaction through a chain reorganization. The more confirmations there are, the more deeply the transaction is embedded in the current valid chain with the highest accumulated work, and the lower the probability of being rolled back. Small-value transactions may accept fewer confirmations, while large-value transactions usually wait for more confirmations to reduce the risk of double spending or chain reorganization.""",
    "What is a double-spending attack?": """A double-spending attack means that an attacker attempts to spend the same bitcoins twice. A typical method is to first broadcast a payment transaction to a merchant while privately constructing another conflicting transaction that sends the same inputs back to themselves. If the attacker can make the chain containing their conflicting transaction obtain higher accumulated work, the payment transaction originally seen by the merchant may be rolled back. Bitcoin reduces the probability of successful double spending through UTXO checks, signature verification, transaction conflict rules, proof of work, and confirmations, but security depends on the attacker's share of hash power, the number of confirmations waited for, and the transaction amount.""",
    "What is UTXO?": """UTXO is the abbreviation of Unspent Transaction Output, meaning an unspent transaction output. It is the basic unit for recording the state of funds in Bitcoin. Bitcoin does not have a traditional bank-style account balance table, but instead uses a set of outputs that have not yet been spent to represent available funds. When initiating a transaction, the wallet selects several UTXOs as inputs and creates new outputs for the recipient and the change address. When nodes verify a transaction, they check whether the UTXOs referenced by the inputs exist, whether they are unspent, whether the scripts and signatures satisfy the conditions, and whether the total input amount is not less than the total output amount.""",
    "What is a Merkle tree?": """A Merkle tree is a tree-like structure that organizes large amounts of data using hash values. Transactions in a Bitcoin block are first individually hashed, then paired and hashed repeatedly, ultimately producing a Merkle root. The Merkle root is written into the block header and summarizes the entire transaction set of the block with a fixed-length hash value. With a Merkle tree, light nodes can use Merkle proofs to verify whether a transaction is included in a certain block without downloading all transactions in the block, so it improves the efficiency of data integrity verification and lightweight verification.""",
    "What is a consensus mechanism?": """A consensus mechanism is a method in a distributed system that allows multiple participants to agree on the same state or historical record without a central coordinator. In a blockchain, the consensus mechanism specifies how transactions are verified, how blocks are produced, how conflicting chains are selected, and how invalid blocks are rejected. Bitcoin uses proof of work and the valid-chain rule with the highest accumulated work, allowing nodes to choose the same history in an open network. A consensus mechanism is not only a block production algorithm, but also includes transaction format, supply cap, block rules, and script verification rules executed by nodes.""",
    "What are the advantages of decentralization?": """The advantages of decentralization are that the system does not rely on a single manager, single server, or single database, so it has stronger fault tolerance, censorship resistance, and open participation. Anyone can independently run a node to verify the rules, reducing reliance on trusted third-party accounting institutions. The shutdown, attack, or departure of individual nodes does not cause the entire system to stop. Decentralization also improves rule transparency and auditability, because the ledger and verification rules can be checked by users themselves rather than completely relying on the statement of a certain institution.""",
    "What are the disadvantages of decentralization?": """Decentralized systems usually sacrifice some efficiency, governance speed, and user experience. Because many nodes need to repeatedly verify and synchronize data, throughput, latency, and storage costs are often not as good as centralized databases. Rule upgrades require relatively broad ecosystem consensus, and the coordination process is complex and may produce disagreements. Users managing their own private keys also transfers responsibility to them. If a private key or mnemonic phrase is lost, assets usually cannot be recovered through central customer service; if a key is leaked, an attacker may directly transfer the funds.""",
    "What is a smart contract?": """A smart contract is a set of programmable rules deployed on a blockchain or similar distributed system, which can automatically execute state changes or asset transfers according to preset conditions. It is not a traditional legal contract itself, but rather writes part of the business logic into verifiable and executable code. Smart contracts are commonly used for token issuance, decentralized exchanges, lending, governance, custody, and automatic settlement. Their advantages are public execution, verifiable results, and reduced reliance on intermediaries; their disadvantages are that code vulnerabilities, oracle errors, permission design mistakes, and economic attacks may cause serious losses.""",
    "What is a stablecoin?": """A stablecoin is a type of crypto asset that attempts to keep its price pegged to some external asset, with the common peg being fiat currency such as the US dollar. Stablecoins can maintain price through fiat reserves, short-term asset reserves, over-collateralized crypto assets, or algorithmic adjustment mechanisms. They are commonly used for on-chain payments, transaction settlement, cross-platform transfers, and DeFi applications. Key issues for stablecoins include reserve authenticity, redemption mechanisms, issuer credit, regulatory risks, collateral volatility, liquidation mechanisms, and depegging risks under extreme market conditions.""",
    "What is the difference between cryptocurrency and blockchain?": """Blockchain is a distributed ledger structure and state synchronization technology used to record transactions, data, or program states; cryptocurrency is a typical application on a blockchain, used to represent value, pay transaction fees, or incentivize network participants. Bitcoin is both a cryptocurrency and a blockchain network. Not all blockchains must issue publicly traded tokens, and not all digital assets have the same degree of decentralization, security, or censorship resistance.""",
    "What is a mnemonic phrase?": """A mnemonic phrase is a group of words generated according to a fixed word list and checksum rules, used to make wallet backup and recovery more convenient. Many wallets use schemes similar to BIP39, encoding random entropy into a mnemonic phrase, then deriving a seed from the mnemonic phrase and an optional passphrase, and then using the seed to generate many private keys, public keys, and addresses for hierarchical deterministic wallets. A mnemonic phrase is not an ordinary login password, but the root material for restoring wallet control; whoever possesses the mnemonic phrase can usually restore and control the assets in the corresponding wallet.""",
    "What is a hardware wallet?": """A hardware wallet is a form of wallet that keeps private keys in a dedicated hardware device. It usually keeps private keys inside the device, signs transaction digests inside the device, and lets the external computer or phone only construct transactions, display information, and broadcast signed results. Hardware wallets can reduce the risk of malware on networked devices directly stealing private keys, and can reduce phishing risks by confirming addresses and amounts on the screen. They are suitable for long-term storage of crypto assets, but still require correct backup of mnemonic phrases, verification of transaction information, and protection against supply chain and social engineering attacks.""",
    "What is a multisig wallet?": """A multisig wallet is a wallet structure that requires several out of multiple private keys to jointly authorize spending funds. For example, 2-of-3 multisig means there are three keys in total, and any two valid signatures can spend the funds. Multisig can reduce the risk caused by the loss or theft of a single private key, and is also suitable for enterprise fund management, family co-custody, custodial services, and disaster recovery schemes. The key to multisig lies in properly distributing keys, saving the redeem script or descriptor, testing the recovery process, and avoiding all keys being placed on the same device or in the same location.""",
    "What is the difference between a public blockchain and a consortium blockchain?": """A public blockchain is usually open to everyone. Anyone can read data, send transactions, run nodes, and participate in consensus when satisfying the rules. Its typical goals are openness, censorship resistance, and trust minimization. A consortium blockchain is usually jointly maintained by a group of known institutions, with more controlled node access, permissions, identities, and governance rules, making performance, compliance, and privacy management easier to optimize. Both may use blockchain structures, but their trust models are different: public blockchains rely more on open consensus and economic incentives, while consortium blockchains rely more on participating institutions and permission governance.""",
    "What is the difference between symmetric encryption and asymmetric encryption?": """Symmetric encryption uses the same key for encryption and decryption. It is fast and suitable for encrypting large amounts of data, but key distribution and key management are difficult. Asymmetric cryptography uses two types of related keys: public keys and private keys. Public keys can be made public, while private keys must be kept secret. It is commonly used for digital signatures, identity authentication, and key exchange. Actual secure communication usually combines the two: first using asymmetric cryptography to complete identity authentication and session key negotiation, and then using symmetric encryption or AEAD algorithms to efficiently protect large amounts of communication data.""",
    "What is ChaCha20?": """ChaCha20 is a symmetric stream cipher algorithm that uses a 256-bit key, nonce, and counter to generate a pseudorandom keystream, and then XORs the keystream with plaintext to obtain ciphertext. It is suitable for software implementation and performs well on many devices without AES hardware acceleration. ChaCha20 only provides confidentiality, meaning that it makes it difficult for attackers to read the plaintext; it does not provide integrity or source authentication by itself. If the same key and nonce combination is reused for different messages, the security of the stream cipher will be seriously compromised.""",
    "What is Poly1305?": """Poly1305 is a message authentication code algorithm used to verify data integrity and authenticity. It computes an authentication tag based on a key and a message, and the receiver recomputes the tag with the same key and compares it, thereby determining whether the message has been tampered with and whether it comes from a party holding the key. Poly1305 is not responsible for encrypting plaintext, so it cannot provide confidentiality by itself. In actual protocols, Poly1305 is often combined with ChaCha20, where ChaCha20 generates a one-time authentication key and Poly1305 authenticates ciphertext and associated data.""",
    "What is ChaCha20-Poly1305?": """ChaCha20-Poly1305 is an AEAD authenticated encryption algorithm that combines the stream encryption capability of ChaCha20 and the message authentication capability of Poly1305. ChaCha20 is used to encrypt plaintext, while Poly1305 is used to generate an authentication tag, protecting ciphertext and associated data from tampering. It can provide confidentiality, integrity, and authenticity at the same time, and is common in TLS, QUIC, VPNs, mobile communications, and modern security protocols. When using it, the nonce must be guaranteed not to repeat under the same key, otherwise confidentiality and authentication security may be broken.""",
    "What does AEAD mean?": """AEAD is the abbreviation of Authenticated Encryption with Associated Data, meaning authenticated encryption with associated data. It encrypts plaintext while generating an authentication tag for the ciphertext and additional data. The additional data is not encrypted, but its integrity is protected, such as protocol headers, version numbers, sequence numbers, or routing metadata. The receiver should accept the decrypted result only after the authentication tag is verified successfully. The advantage of AEAD is that it combines encryption and authentication into a clear interface, reducing security problems caused by encrypting without authentication or using the wrong authentication order.""",
    "What does nonce mean in encryption?": """Nonce is the abbreviation of number used once, meaning a value that should be used only once under a specific key. Many encryption algorithms combine a nonce with a key, counter, or message sequence number to ensure that the same plaintext produces different ciphertexts under different nonces. A nonce usually does not need to be secret, but it must meet the uniqueness or randomness requirements of the algorithm. For AEAD algorithms such as ChaCha20-Poly1305, repeating a nonce under the same key causes keystream reuse and may reveal relationships between plaintexts or invalidate authentication security.""",
    "What is key exchange?": """Key exchange is the process by which two communicating parties negotiate a shared secret over an insecure network. Typical methods include Diffie-Hellman and elliptic curve Diffie-Hellman. Each party generates a private random number and exchanges the corresponding public value, then obtains the same shared secret through mathematical operations; even if an observer sees the public values, it is difficult to compute the secret. The negotiated shared secret is usually not used directly as an encryption key, but is input into a key derivation function such as HKDF to generate key material for AEAD encryption, message authentication, and session protection.""",
    "What is X25519?": """X25519 is an elliptic curve Diffie-Hellman key exchange algorithm based on Curve25519, used to let communicating parties negotiate a shared secret. It is not an encryption algorithm or a digital signature algorithm, but a key agreement algorithm. X25519 has characteristics such as simple implementation, good performance, and relatively strong resistance to some implementation errors, and is commonly used in modern security protocols such as TLS, WireGuard, and Signal. Actual systems usually input the shared secret obtained from X25519 into a key derivation function and then derive symmetric encryption keys.""",
    "What is Ed25519?": """Ed25519 is a digital signature algorithm based on an Edwards curve, used for identity authentication, message integrity verification, and authorization proof. It and X25519 are both related to the Curve25519 family, but their uses are different: X25519 is used for key exchange, while Ed25519 is used for digital signatures. Ed25519 has fast signing, short signatures, and efficient verification, and is very common in modern protocols and software supply chain signing. When using it, the private key must be protected, and the implementation must correctly handle message encoding, randomness, or deterministic signing processes.""",
    "What is end-to-end encryption?": """End-to-end encryption means that messages are encrypted at the sending end and only the intended receiving end can decrypt them. Intermediate servers, network operators, or forwarding nodes cannot read the plaintext content. It is usually implemented by combining identity keys, key exchange, session keys, AEAD, message authentication codes, and key rotation mechanisms. End-to-end encryption can protect communication content from being read or tampered with by intermediate nodes, but it does not automatically hide all metadata, such as the communicating parties, time, frequency, and message size, nor can it replace the security protection of endpoint devices themselves.""",
    "What is a zero-knowledge proof?": """A zero-knowledge proof is a cryptographic protocol that allows a prover to prove to a verifier that a statement is true without revealing any additional information beyond the truth of the statement. For example, a prover can prove that they know a certain secret, or prove that a transaction satisfies balance and rule constraints, without disclosing the secret or complete transaction details. Zero-knowledge proofs are commonly used in privacy protection, identity authentication, blockchain scaling, validity proofs, and compliance proofs. Common systems focus on completeness, soundness, zero-knowledge property, proof size, verification speed, and trusted setup.""",
    "What is a hash commitment?": """A hash commitment is a commitment mechanism implemented with a hash function. The committing party first calculates and publishes the hash value of secret data together with a random salt, which is equivalent to locking in a choice first; later, the original data and random salt are disclosed, and the verifier recalculates the hash value to confirm whether the commitment is consistent. Hash commitments have hiding and binding properties: when the hash is public, others have difficulty knowing the secret content, but the committing party also has difficulty changing it to another content later. It is commonly used in lotteries, voting, protocol negotiation, and blockchain interactions.""",
    "Why are random numbers important in cryptography?": """Random numbers are very important in cryptography because key generation, nonces, signatures, key exchange, and challenge-response mechanisms may all rely on unpredictable data. High-quality random numbers can prevent attackers from guessing keys, replaying protocols, or recovering private keys. Insufficient random number quality can lead to serious vulnerabilities. For example, repeated signing random numbers may leak digital signature private keys, and repeated stream cipher nonces may reveal relationships between plaintexts. Cryptographic systems usually need to use secure random number generators rather than ordinary pseudorandom functions or timestamps.""",
    "What is the difference between hashing and encryption?": """Hashing and encryption have different goals. Hashing is a one-way digest function that turns input of arbitrary length into fixed-length output. It usually cannot restore the original text from the hash value and is commonly used for integrity checks, indexing, commitments, and proof of work. Encryption is a reversible transformation that turns plaintext into ciphertext, and whoever holds the correct key can decrypt it and recover the plaintext. Hashing does not require a decryption key, while encryption relies on keys to protect confidentiality. Cryptographic systems often use hashing, encryption, signatures, and message authentication codes together, but they undertake different security goals."""
})
model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-mpnet-base-v2")
questions = list(qa_data.keys())
vectors = model.encode(
    questions,
    convert_to_numpy=True,
    normalize_embeddings=True
).astype("float32")
dim = vectors.shape[1]
index = faiss.IndexFlatIP(dim)
# Insert data
index.add(vectors)
def search(query, top_k=1):
    query_vector = model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")
    scores, ids = index.search(query_vector, top_k)
    idx = ids[0][0]
    score = scores[0][0]
    matched_question = questions[idx]
    answer = qa_data[matched_question]
    return answer, matched_question, float(score)


while True:
    query = input("Please enter a question, enter q to exit: ").strip()
    if query.lower() in ["q", "quit", "exit"]:
        break
    answer, matched_question, score = search(query)
    print("Answer:", answer)
    print("Matched question:", matched_question)
    print("Similarity:", score)
    print()
